# fly.toml app configuration file generated for weatherman-d-t-5-1719240084-client on 2024-06-24T14:42:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weatherman-d-t-5-1719240084-client'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 4
